# Generated by Django 3.0.4 on 2020-03-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=255, verbose_name='매치이름')),
                ('red_team_name', models.CharField(max_length=255, verbose_name='레드팀명')),
                ('blue_team_name', models.CharField(max_length=255, verbose_name='블루팀명')),
                ('password', models.CharField(max_length=255, verbose_name='패스워드')),
                ('banpick', models.CharField(max_length=255, verbose_name='밴픽Data')),
            ],
        ),
    ]
