# Generated by Django 3.0.4 on 2020-04-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='이름/별칭')),
                ('sm_pic', models.ImageField(upload_to='', verbose_name='작은이미지')),
                ('lg_pic', models.ImageField(upload_to='', verbose_name='큰이미지')),
            ],
            options={
                'verbose_name': '챔피언',
                'verbose_name_plural': '챔피언',
            },
        ),
        migrations.AlterModelOptions(
            name='draft',
            options={'verbose_name': '밴픽', 'verbose_name_plural': '밴픽'},
        ),
        migrations.AlterField(
            model_name='draft',
            name='blue_team_name',
            field=models.CharField(max_length=255, verbose_name='블루팀 팀명'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='match_name',
            field=models.CharField(max_length=255, verbose_name='매치 이름'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='red_team_name',
            field=models.CharField(max_length=255, verbose_name='레드팀 팀명'),
        ),
    ]
