# Generated by Django 3.0.4 on 2020-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='blue_player_name',
            field=models.CharField(default='', max_length=100, verbose_name='블루팀 플레이어명'),
        ),
        migrations.AddField(
            model_name='draft',
            name='red_player_name',
            field=models.CharField(default='', max_length=100, verbose_name='레드팀 플레이어명'),
        ),
    ]
