# Generated by Django 3.0.4 on 2020-04-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20200426_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='timer',
            field=models.IntegerField(blank=True, default=0, verbose_name='타이머'),
        ),
    ]
