# Generated by Django 3.0.4 on 2020-04-01 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20200401_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='일시'),
        ),
    ]
