# Generated by Django 3.0.4 on 2020-04-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_auto_20200430_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='timer',
            field=models.IntegerField(blank=True, null=True, verbose_name='타이머'),
        ),
    ]
