# Generated by Django 3.0.4 on 2020-04-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_draft_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='lane',
            field=models.CharField(default='', max_length=20, verbose_name='라인'),
        ),
    ]
