# Generated by Django 3.0.4 on 2020-05-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20200430_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='timer',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시작'),
        ),
    ]
