# Generated by Django 3.0.4 on 2020-04-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_champion_lane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(default='', help_text='/ 로 구분해주세요.', max_length=255, verbose_name='이름/별칭'),
        ),
    ]
