# Generated by Django 3.0.4 on 2020-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_auto_20200501_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='banpick_final',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='밴픽최종'),
        ),
    ]
