# Generated by Django 3.0.4 on 2020-04-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_auto_20200401_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='lg_pic',
        ),
        migrations.RemoveField(
            model_name='champion',
            name='sm_pic',
        ),
        migrations.AddField(
            model_name='champion',
            name='keyword',
            field=models.CharField(default='', help_text='"/" 로 구분해주세요. ex)가렌/garen', max_length=255, verbose_name='검색어'),
        ),
        migrations.AddField(
            model_name='champion',
            name='no',
            field=models.CharField(default='', max_length=3, verbose_name='챔피언번호'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='lane',
            field=models.CharField(default='', help_text='한글로 입력해주세요. ex)탑/미드', max_length=20, verbose_name='라인'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='name',
            field=models.CharField(default='', help_text='한글로 입력해주세요. ex)가렌', max_length=20, verbose_name='챔피언명'),
        ),
    ]
