# Generated by Django 3.0.4 on 2020-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_auto_20200401_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='banpick',
            field=models.CharField(blank=True, max_length=255, verbose_name='밴픽Data'),
        ),
    ]
