# Generated by Django 3.0.4 on 2020-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_draft_banpick_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='banpick_final',
        ),
        migrations.AddField(
            model_name='draft',
            name='banpick_final_blue',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='블루픽'),
        ),
        migrations.AddField(
            model_name='draft',
            name='banpick_final_red',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='레드픽'),
        ),
    ]
