# Generated by Django 3.0.4 on 2020-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_auto_20200405_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='시작'),
        ),
    ]
