# Generated by Django 3.0.4 on 2020-07-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_auto_20200627_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='banpick_final_blue',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='banpick_final_red',
        ),
        migrations.AddField(
            model_name='draft',
            name='banpick_final',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='밴픽최종'),
        ),
    ]
