# Generated by Django 3.0.4 on 2020-07-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_auto_20200702_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='blue_done',
            field=models.BooleanField(default=False, verbose_name='블루팀 라인'),
        ),
        migrations.AddField(
            model_name='draft',
            name='red_done',
            field=models.BooleanField(default=False, verbose_name='레드팀 라인'),
        ),
    ]
