# Generated by Django 3.0.4 on 2020-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_draft_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='start',
            field=models.DateTimeField(blank=True, verbose_name='시작'),
        ),
    ]
