# Generated by Django 3.0.4 on 2020-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0009_auto_20200702_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='방 코드'),
        ),
    ]
