# Generated by Django 3.0.4 on 2021-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0010_draft_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='mode',
            field=models.CharField(choices=[('1', 'Single Play'), ('2', 'Multi Play')], default='1', max_length=20, verbose_name='모드'),
        ),
    ]
