# Generated by Django 3.0.4 on 2020-04-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0010_auto_20200405_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='start',
            new_name='timer',
        ),
    ]
